services:
  db:
    build: ./db
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
  backend:
    build: ./backend
    container_name: backend
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/messenger_db
      JWT_SECRET: super-secret-change-me
      CLIENT_URL: "*"
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: /api
        NEXT_PUBLIC_TURN_SERVER: ${NEXT_PUBLIC_TURN_SERVER:-}
        NEXT_PUBLIC_TURN_USERNAME: ${NEXT_PUBLIC_TURN_USERNAME:-}
        NEXT_PUBLIC_TURN_CREDENTIAL: ${NEXT_PUBLIC_TURN_CREDENTIAL:-}
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
